acceleration: none #set this to 'fast' to see performance stability
deletechestminecart: false #Set to true to delete chested minecart entity
fpstexturepack: true #Will set server's texture pack to a FPS Boost texture pack