#########################
#Server Optimization    # -> This category focuses on general server optimization
#########################

#acceleration ('false' / 'true') focuses on the optimization of files. Performance wise: heavy change.
acceleration: true
#deletechestminecart ('false' / 'true') focuses on the removal of minecart chests. Performance: small-medium change (matters on server's size)
deletechestminecart: false
#fpstexturepack ('false / 'true') gives users an option to change their texture pack to the barebones texture pack which can help with client's fps. Performance: Users that uses integrated graphics (iGPUs) can expect a boost in FPS.
fpstexturepack: false
#smarterRedstone -> set acceleration 'true' ('false' / 'true') replaces the redstone system with faster and alternative versions that reduce redundant block updates, lowering the amount of logic your server has to calculate. Performance: small-medium change (matters on redstone usage on server)
smarterRedstone: false

#SERVER PROPERTIES EDITING
#Simulation Distance (Lower is Better, Recommended: 5, Default: 10)-> # of chunks around the player that the server will tick.
simulationd: 10
#View Distance (Lower is Better, Recommended: 7-8, Default: 10) -> Distance (in chunks) that will be sent to players. Less View Distance -> More FPS!
viewd: 10

#########################
#Combatting Lag Machines# -> This category focuses on certain parts of the game that can be weaponized as lag machines.
#########################

#nerfsnowman. ('false' / 'true') Disables the A.I. for snowman. They will no longer move or shoot snowballs. Snowman (and snowballs) are recognized as entities and a collection of them can hurt server's TPS.
nerfsnowman: false