acceleration: normal #options are "none", "normal" or "fast" - Normal applies some change. Fast applies heavy speeds.
spigotedit: True
paperedit: True
bukkitedit: True

#For the edits, if it's set to "True" then the .jar plugin will optimize the files. If it's set to "False" then it will not touch it.